EXERCISE-5 Add cards to index.html
js-tasks-ru/htmlcss-20220120_labudova81 pull request #10
Opened 2022-02-10 10:47 UTC by yuliyalabudovaa

2022-02-10 10:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-10 11:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-10 14:57 UTC, GSemikozov requested changes

2022-02-10 14:57 UTC, GSemikozov commented on components/card/card.css
> +.card__body {
надо подумать как сделать так чтобы боди всегда был прижат к низу карточки (тогда тайтлы всегда будут на одном уровне не зависимо от высоту превью)

2022-02-11 11:33 UTC, yuliyalabudovaa commented on components/card/card.css
> +.card__body {
спасибо, исправила

2022-02-13 20:47 UTC, GSemikozov approved these changes

2022-02-13 20:47 UTC, merged