EXERCISE-6 Add solution for background image
js-tasks-ru/htmlcss-20220120_labudova81 pull request #12
Opened 2022-02-11 21:04 UTC by yuliyalabudovaa

2022-02-11 21:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-16 21:09 UTC, GSemikozov requested changes

2022-02-16 21:09 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 480px) {
по медиа-запросам - лучше выбрать 1 подход и двигаться либо сверху вниз, либо снизу вверх (= использовать либо max-width, либо min-width)

2022-02-16 21:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-16 21:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-16 21:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-16 21:44 UTC, yuliyalabudovaa commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 480px) {
спасибо, исправила

2022-02-16 21:46 UTC, GSemikozov approved these changes

2022-02-16 21:46 UTC, merged