EXERCISE-3 Add accordion + main page
js-tasks-ru/htmlcss-20220120_labudova81 pull request #4
Opened 2022-01-30 19:14 UTC by yuliyalabudovaa

2022-01-30 19:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-31 06:51 UTC, GSemikozov requested changes

2022-01-31 06:51 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 1rem;
это скорее внутренние отступы

2022-01-31 06:51 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 0.5rem;
марджины на уровне блока не задаем. Но - можем улучшить верстку: .accordion переименовать в .accordion__item, и все items обернуть в div с классом .accordion - так структурно, логически и семантически компонент будет более цельным

2022-01-31 14:35 UTC, yuliyalabudovaa commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 1rem;
спасибо, исправила

2022-01-31 14:35 UTC, yuliyalabudovaa commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 0.5rem;
спасибо, исправила

2022-01-31 21:45 UTC, GSemikozov approved these changes

2022-01-31 21:45 UTC, merged