EXERCISE-4 Add skeleton
js-tasks-ru/htmlcss-20220120_labudova81 pull request #5
Opened 2022-01-30 20:53 UTC by yuliyalabudovaa

2022-01-30 20:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-31 07:05 UTC, GSemikozov requested changes

2022-01-31 07:05 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__lines {
.skeleton__header__lines -> .skeleton__header-lines

2022-01-31 07:05 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__small-line {
.skeleton__line_small-line

2022-01-31 07:05 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__big-line {
.skeleton__header__big-line -> .skeleton__line_big-line

2022-01-31 07:05 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__body__line {
.skeleton__line_body-line

2022-01-31 14:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-31 14:41 UTC, yuliyalabudovaa commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__lines {
спасибо, исправила

2022-01-31 14:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-31 14:41 UTC, yuliyalabudovaa commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__small-line {
спасибо, исправила

2022-01-31 14:41 UTC, yuliyalabudovaa commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__body__line {
спасибо, исправила

2022-01-31 14:42 UTC, yuliyalabudovaa commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__big-line {
спасибо, исправила

2022-01-31 21:45 UTC, GSemikozov approved these changes, later dismissed

2022-01-31 21:45 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-02-01 11:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-01 13:45 UTC, GSemikozov requested changes

2022-02-01 13:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
тут лучше в процентах - например 33%, и ниже тоже

2022-02-01 14:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-01 14:27 UTC, GSemikozov approved these changes

2022-02-01 14:27 UTC, merged