EXERCISE-5 Add histogram
js-tasks-ru/htmlcss-20220120_labudova81 pull request #8
Opened 2022-02-07 19:54 UTC by yuliyalabudovaa

2022-02-07 19:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-07 21:34 UTC, GSemikozov requested changes

2022-02-07 21:34 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: inherit;
а от чего inherit? тут все-таки лучше например flex-basis: 9px

2022-02-07 21:34 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +
я бы советовал здесь задать фиксированную высоту, чтобы ниже колонкам задавать высоту в процентах (ка раз таки относительно этого значения)

2022-02-08 15:02 UTC, GSemikozov approved these changes

2022-02-08 15:02 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-02-08 15:03 UTC, GSemikozov approved these changes

2022-02-08 15:03 UTC, merged